#====================#
#=== EXAMPLE INFO ===#

[package]
  authors.workspace = true
  edition.workspace = true
  name              = "text3d"
  publish           = false
  version.workspace = true

  #===============================#
  #=== DEPENDENCIES & FEATURES ===#

[dependencies]
  bevy       = { version = "0.20", default-features = true }
  bevy_lunex = { workspace = true }
